CMTE_DSGN = {
    'A': 'Authorized by a candidate',
    'B': 'Lobbyist/Registrant PAC',
    'D': 'Leadership PAC',
    'J': 'Joint fundraiser',
    'P': 'Principal campaign committee of a candidate',
    'U': 'Unauthorized'
}

#http://www.fec.gov/finance/disclosure/metadata/CommitteeTypeCodes.shtml
CMTE_TP = {
'C' : 'Communication Cost',
'D' : 'Delegate Committee',
'E':  'Electioneering Communication Groups',
'H' : 'House',
'I' : 'Independent Expenditor (Person or Group)',
'N': 'PAC - Nonqualified',
'O': 'Independent Expenditure-Only (Super PACs)',
'P': 'Presidential',
'Q': 'PAC - Qualified',
'S': 'Senate',
'U': 'Single Candidate Independent Expenditure',
'V': 'PAC with Non-Contribution Account - Nonqualified',
'W': 'PAC with Non-Contribution Account - Qualified',
'X': 'Party - Nonqualified',
'Y': 'Party - Qualified',
'Z': 'National Party Nonfederal Account'
}

CMTE_PTY_AFFILIATION = {
'ACE':'Ace Party',
'GOP':'GOP',
'AKI':'Alaskan Independence Party',
'AIC':'American Independent Conservative',
'AIP':'American Independent Party',
'AMP':'American Party',
'APF':'American Peoples Freedom Party',
'AE':'Americans Elect',
'CIT':'Citizens Party',
'CMD':'Commandments Party',
'CMP':'Commonwealth Party of the U.S.',
'COM':'Communist Party',
'CNC':'Concerned Citizens Party Of Connecticut',
'CRV':'Conservative Party',
'CON':'Constitution Party',
'CST':'Constitutional',
'COU':'Country',
'DCG':'D.C. Statehood Green Party',
'DNL':'Democratic -Nonpartisan League',
'DEM':'Democratic Party',
'D/C':'Democratic/Conservative',
'DFL':'Democratic-Farmer-Labor',
'DGR':'Desert Green Party',
'FED':'Federalist',
'FLP':'Freedom Labor Party',
'FRE':'Freedom Party',
'GWP':'George Wallace Party',
'GRT':'Grassroots',
'GRE':'Green Party',
'GR':'Green-Rainbow',
'HRP':'Human Rights Party',
'IDP':'Independence Party',
'IND':'Independent',
'IAP':'Independent American Party',
'ICD':'Independent Conservative Democratic',
'IGR':'Independent Green',
'IP':'Independent Party',
'IDE':'Independent Party of Delaware',
'IGD':'Industrial Government Party',
'JCN':'Jewish/Christian National',
'JUS':'Justice Party',
'LRU':'La Raza Unida',
'LBR':'Labor Party',
'LFT':'Less Federal Taxes',
'LBL':'Liberal Party',
'LIB':'Libertarian Party',
'LBU':'Liberty Union Party',
'MTP':'Mountain Party',
'NDP':'National Democratic Party',
'NLP':'Natural Law Party',
'NA':'New Alliance',
'NJC':'New Jersey Conservative Party',
'NPP':'New Progressive Party',
'NPA':'No Party Affiliation',
'NOP':'No Party Preference',
'NNE':'None',
'N':'Nonpartisan',
'NON':'Non-Party',
'OE':'One Earth Party',
'OTH':'Other',
'PG':'Pacific Green',
'PSL':'Party for Socialism and Liberation',
'PAF':'Peace And Freedom',
'PFP':'Peace And Freedom Party',
'PFD':'Peace Freedom Party',
'POP':'People Over Politics',
'PPY':'Peoples Party',
'PCH':'Personal Choice Party',
'PPD':'Popular Democratic Party',
'PRO':'Progressive Party',
'NAP':'Prohibition Party',
'PRI':'Puerto Rican Independence Party',
'RUP':'Raza Unida Party',
'REF':'Reform Party',
'REP':'Republican Party',
'RES':'Resource Party',
'RTL':'Right To Life',
'SEP':'Socialist Equality Party',
'SLP':'Socialist Labor Party',
'SUS':'Socialist Party',
'SOC':'Socialist Party U.S.A.',
'SWP':'Socialist Workers Party',
'TX':'Taxpayers',
'TWR':'Taxpayers Without Representation',
'TEA':'Tea Party',
'THD':'Theo-Democratic',
'LAB':'U.S. Labor Party',
'USP':'U.S. Peoples Party',
'UST':'U.S. Taxpayers Party',
'UN':'Unaffiliated',
'UC':'United Citizen',
'UNI':'United Party',
'UNK':'Unknown',
'VET':'Veterans Party',
'WTP':'We the People',
'W':'Write-In'
}

CMTE_FILING_FREQ = {
'A': 'Administratively terminated',
'D': 'Debt',
'M': 'Monthly filer',
'Q': 'Quarterly filer',
'T': 'Terminated',
'W': 'Waived',
}
ORG_TP = {
'C': 'Corporation',
'L': 'Labor organization',
'M': 'Membership organization',
'T': 'Trade association',
'V': 'Cooperative',
'W': 'Corporation without capital stock'
}


CAND_OFFICE = {
'H': 'House',
'P': 'President',
'S': 'Seante ',
}

CAND_ICI = {
'C': 'Challenger',
'I': 'Incumbent',
'O': 'Open Seat'}

CAND_STATUS = {
'C': 'Statutory candidate',
'F': 'Statutory candidate for future election',
'N': 'Not yet a statutory candidate',
'P': 'Statutory candidate in prior cycle'
}

TRANSACTION_PGI_c = {
'P': 'Primary',
'G': 'General',
'O': 'Other',
'C': 'Convention',
'R': 'Runoff',
'S': 'Special',
'E': 'Recount'
}

TRANSACTION_TP = {
'10':'Non-Federal Receipt from Persons',
'10J':'Memo Receipt from JF Nonfederal',
'11':'Tribal Contribution',
'11J':'	Memo Receipt from JF Tribal',
'12':'Non-Federal Other Receipt - Levin Account (L-2)',
'13':'Inaugural Donation Accepted',
'15':'Contribution',
'15C':'Contribution from Candidate',
'15E':'Earmarked Contribution',
'15F':'Loans forgiven by Candidate',
'15I':'Earmarked Intermediary In',
'15J':'Memo (Filers Percentage of Contribution Given to Join Fundraising Committee)',
'15T':'Earmarked Intermediary Treasury In',
'15Z':'In-Kind Contribution Received from Registered Filer',
'16C':'Loans Received from the Candidate',
'16F':'Loans Received from Banks',
'16G':'Loan from Individual',
'16H':'Loan from from Registered Filers',
'16J':'Loan Repayments from Individual',
'16K':'Loan Repayments from from Registered Filer',
'16L':'Loan Repayments Received from Unregistered Entity',
'16R':'Loans Received from Registered Filers',
'16U':'Loan Received from Unregistered Entity',
'17R':'Contribution Refund Received from Registered Entity',
'17U':'Refunds/Rebates/Returns Received from Unregistered Entity',
'17Y':'Refunds/Rebates/Returns from Individual or Corporation',
'17Z':'Refunds/Rebates/Returns from Candidate or Committee',
'18G':'Transfer In Affiliated',
'18H':'Honorarium Received',
'18J':'Memo (Filers Percentage of Contribution Given to Join Fundraising Committee)',
'18K':'Contribution Received from Registered Filer',
'18L':'Bundled Contribution',
'18S':'Receipts from Secretary of State',
'18U':'Contribution Received from Unregistered Committee',
'19':'Electioneering Communication Donation Received',
'19J':'Memo (Electioneering Communication Percentage of Donation Given to Join Fundraising Committee)',
'20':'Disbursement - Exempt from Limits',
'20A':'Non-Federal Disbursement - Levin Account (L-4A) Voter Registration',
'20B':'Non-Federal Disbursement - Levin Account (L-4B) Voter Identification',
'20C':'Loan Repayments Made to Candidate',
'20D':'Non-Federal Disbursement - Levin Account (L-4D) Generic Campaign',
'20F':'Loan Repayments Made to Banks',
'20G':'Loan Repayments Made to Individual',
'20R':'Loan Repayments Made to Registered Filer',
'20V':'Non-Federal Disbursement - Levin Account (L-4C) Get Out The Vote',
'20Y' :'Non-Federal Refund',
'21Y':'Tribal Refund',
'22G':'Loan to Individual',
'22H':'Loan to Candidate or Committee',
'22J':'Loan Repayment to Individual',
'22K':'Loan Repayment to Candidate or Committee',
'22L':'Loan Repayment to Bank',
'22R':'Contribution Refund to Unregistered Entity',
'22U':'Loan Repaid to Unregistered Entity',
'22X':'Loan Made to Unregistered Entity',
'22Y':'Contribution Refund to Individual',
'22Z':'Contribution Refund to Candidate or Committee',
'23Y':'Inaugural Donation Refund',
'24A':'Independent Expenditure Against',
'24C':'Coordinated Expenditure',
'24E':'Independent Expenditure For',
'24F':'Communication Cost for Candidate (C7)',
'24G':'Transfer Out Affiliated',
'24H':'Honorarium to Candidate',
'24I':'Earmarked Intermediary Out',
'24K':'Contribution Made to Non-Affiliated',
'24N':'Communication Cost Against Candidate (C7)',
'24P':'Contribution Made to Possible Candidate',
'24R':'Election Recount Disbursement',
'24T':'Earmarked Intermediary Treasury Out',
'24U':'Contribution Made to Unregistered Entity',
'24Z':'In-Kind Contribution Made to Registered Filer',
'28L':'Refund of Bundled Contribution',
'29':'Electioneering Communication Disbursement or Obligation',
'30':'Convention Account Receipt - Individual',
'30T':'Convention Account Receipt - Tribal',
'30K':'Convention Account Receipt - Registered Filer',
'30G' :	'Transfer In - Convention Account',
'30J':'Memo Receipt From Individual - JF Convention Account',
'30F':'Memo Receipt From Registered Filer - JF Convention Account',
'31':'Headquarters Account Receipt- Individual',
'31T': 'Headquarters Account Receipt - Tribal',
'31K': 'Headquarters Account Receipt - Registered Filer',
'31G': 'Transfer In - Headquarters Account',
'31J': 'Memo Receipt From Individual - JF Headquarters Account',
'31F': 'Memo Receipt From Registered Filer - JF Headquarters Account',
'32':'Recount Account Receipt- Individual',
'32T': 'Recount Account Receipt - Tribal',
'32K': 'Recount Account Receipt- Registered Filer',
'32G': 'Transfer In - Recount Account',
'32J':'Memo Receipt From Individual - JF Recount Account',
'40':'Convention Account Disbursement',
'40T':'Convention Account Refund - Tribal',
'41':'Headquarters Account Disbursement',
'41T':'Headquarters Account Refund - Tribal',
'41Y':'Headquarters Account Refund - Individual',
'41Z':'Headquarters Account Refund - Registered Filer',
'40Z':'Convention Account Refund - Registered Filer',
'40Y':'Convention Account Refund - Individual',
'32F':'Memo Receipt From Registered Filer - JF Recount Account',
'42Z':'Recount Account Refund - Registered Filer',
'42Y':'Recount Account Refund - Individual',
'42':'Recount Account Disbursement',
'42T':'Recount Account Refund - Tribal'}

ENTITY_TP = {
'CAN': 'Candidate',
'CCM': 'Candidate Committee',
'COM': 'Committee',
'IND': 'Individual (a person)',
'ORG': 'Organization (not a committee and not a person)',
'PAC': 'Political Action Committee',
'PTY': 'Party Organization',
}


FIELDEXPANSION = {
    'cm':{'CMTE_TP':CMTE_TP,
          'CMTE_DSGN':CMTE_DSGN,
          'CMTE_PTY_AFFILIATION':CMTE_PTY_AFFILIATION,
          'CMTE_FILING_FREQ':CMTE_FILING_FREQ,
          'ORG_TP':ORG_TP
          },
    'cn' : {
        'CAND_PTY_AFFILIATION':CMTE_PTY_AFFILIATION,
        'CAND_OFFICE':CAND_OFFICE,
        'CAND_ICI' : CAND_ICI,
        'CAND_STATUS': CAND_STATUS
        },
    'indiv' : {
        'ENTITY_TP': ENTITY_TP,
        'TRANSACTION_TP': TRANSACTION_TP
    }
}